/**
 * SaleOrder Model
 * Interfaces for SaleOrder management based on backend DTOs
 */

/**
 * Main SaleOrder interface matching SaleOrderDto from backend
 */
export interface SaleOrder {
  id: number;
  customerId: number;
  orderNumber: string;
  orderDate: Date | string;
  deliveryDate: Date | string | null;
  isExchangeSale: boolean;
  exchangeOrderId?: number | null;
  exchangeOrderNumber?: string | null;
  statusId: number;
}

/**
 * Interface for creating a new sale order
 * Note: orderNumber is auto-generated by backend
 */
export interface SaleOrderCreate {
  customerId: number;
  orderDate: Date | string;
  deliveryDate?: Date | string | null;
  isExchangeSale: boolean;
  exchangeOrderId?: number | null;
  statusId: number;
}

/**
 * Interface for updating an existing sale order
 * Note: orderNumber is auto-generated by backend and cannot be updated
 */
export interface SaleOrderUpdate {
  id: number;
  customerId: number;
  orderDate: Date | string;
  deliveryDate?: Date | string | null;
  isExchangeSale: boolean;
  exchangeOrderId?: number | null;
  statusId: number;
}

/**
 * Helper function to get status label based on status ID
 */
export function getStatusLabel(statusId: number): string {
  switch (statusId) {
    case 1:
      return 'Active';
    case 2:
      return 'Inactive';
    case 3:
      return 'Pending';
    case 4:
      return 'Completed';
    case 5:
      return 'Cancelled';
    default:
      return 'Unknown';
  }
}

/**
 * Helper function to get status CSS class based on status ID
 */
export function getStatusClass(statusId: number): string {
  switch (statusId) {
    case 1:
      return 'badge bg-success';
    case 2:
      return 'badge bg-danger';
    case 3:
      return 'badge bg-warning';
    case 4:
      return 'badge bg-primary';
    case 5:
      return 'badge bg-secondary';
    default:
      return 'badge bg-secondary';
  }
}

/**
 * Helper function to format date for display
 */
export function formatDate(date: Date | string | null): string {
  if (!date) return '-';
  const d = new Date(date);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}
