using System;
using System.Collections.Generic;

namespace InventoryManagementSytem.Common.Dtos
{
    /// <summary>
    /// Request DTO for generating an invoice from a sale order
    /// </summary>
    public class InvoiceRequestDto
    {
        public long SaleOrderId { get; set; }
        public bool IncludePaymentDetails { get; set; } = true;
        public bool IncludeTermsAndConditions { get; set; } = true;
        public string? Notes { get; set; }
    }

    /// <summary>
    /// Invoice response with complete jewellery-specific details
    /// </summary>
    public class InvoiceResponseDto
    {
        public long Id { get; set; }

        // Invoice Header
        public string InvoiceNumber { get; set; } = string.Empty;
        public DateTime InvoiceDate { get; set; }
        public string? InvoiceType { get; set; } // "Tax Invoice", "Retail Invoice", "Exchange Invoice"

        // Company Details
        public string CompanyName { get; set; } = string.Empty;
        public string? CompanyAddress { get; set; }
        public string? CompanyPhone { get; set; }
        public string? CompanyEmail { get; set; }
        public string? CompanyGSTIN { get; set; }
        public string? CompanyPAN { get; set; } 

        // Customer/Party Details
        public long PartyId { get; set; }
        public string PartyType { get; set; } = string.Empty;
        public string PartyName { get; set; } = string.Empty;
        public string? PartyAddress { get; set; }
        public string? PartyPhone { get; set; }
        public string? PartyEmail { get; set; }
        public string? PartyGSTIN { get; set; }
        public string? PartyPANNUmber { get; set; }

        // Sale Order Reference
        public long? SaleOrderId { get; set; }
        public long? PurchaseOrderId { get; set; }
        public string OrderNumber { get; set; } = string.Empty;
        public DateTime OrderDate { get; set; }
        public DateTime? DeliveryDate { get; set; }

        // Items
        public List<InvoiceItemDto> Items { get; set; } = new();

        // Pricing Summary
        public decimal SubTotal { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal CGSTAmount { get; set; }
        public decimal SGSTAmount { get; set; }
        public decimal IGSTAmount { get; set; }
        public decimal TotalGSTAmount { get; set; }
        public decimal RoundOff { get; set; }
        public decimal GrandTotal { get; set; }
        public string GrandTotalInWords { get; set; } = string.Empty;

        // TCS Fields (Tax Collected at Source) - Applicable for B2C sales > ₹10 lakh
        public bool IsTcsApplicable { get; set; }
        public decimal TcsRate { get; set; }
        public decimal TcsAmount { get; set; }
        public string? TcsType { get; set; } // "WithPAN", "WithoutPAN", "BelowThreshold"
        public decimal CumulativeSaleAmount { get; set; }
        public bool HasValidPAN { get; set; }
        public string? CustomerPAN { get; set; }
        public decimal GrandTotalWithTcs { get; set; }

        // Payment Details
        public decimal TotalPaid { get; set; }
        public decimal BalanceDue { get; set; }
        public List<InvoicePaymentDto> Payments { get; set; } = new();

        // Jewellery-Specific Details
        public decimal? TotalGoldWeight { get; set; }
        public decimal? TotalStoneWeight { get; set; }
        public int? TotalPieces { get; set; }

        // Footer
        public bool IncludeTermsAndConditions { get; set; } = true;
        public string? TermsAndConditions { get; set; }
        public string? ReturnPolicy { get; set; }
        public string? Notes { get; set; }
        public string? Declaration { get; set; }

        // Audit fields
        public DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int StatusId { get; set; }

        // E-Invoice Fields (GST Compliance)
        public string? IRN { get; set; } // Invoice Reference Number
        public DateTime? IRNGeneratedDate { get; set; }
        public string? QRCode { get; set; } // Base64 QR code
        public string? EInvoiceStatus { get; set; } // Generated, Cancelled, Error
        public DateTime? EInvoiceCancelledDate { get; set; }
        public string? EInvoiceCancelReason { get; set; }
        public string? AcknowledgementNumber { get; set; }
        public DateTime? AcknowledgementDate { get; set; }

        // Generated By
        public string GeneratedBy { get; set; } = string.Empty;
        public DateTime GeneratedAt { get; set; }
    }

    /// <summary>
    /// Individual jewellery item in the invoice
    /// </summary>
    public class InvoiceItemDto
    {
        public long Id { get; set; }
        public long? ReferenceItemId { get; set; }
        public string ItemName { get; set; } = string.Empty;
        public int Quantity { get; set; }

        // Metal Details
        public int MetalId { get; set; }
        public int PurityId { get; set; }
        public string? MetalType { get; set; }
        public string? Purity { get; set; }
        public decimal? GrossWeight { get; set; }
        public decimal? NetMetalWeight { get; set; }
        public decimal? MetalAmount { get; set; }

        // Stone Details
        public int? StoneId { get; set; }
        public decimal? StoneWeight { get; set; }
        public decimal? StoneAmount { get; set; }
        public string? StoneType { get; set; }
        public int? StonePieces { get; set; }
        public string? StoneDetails { get; set; }

        // Making Charges
        public decimal? MakingCharges { get; set; }
        public decimal? WastageAmount { get; set; }
        public decimal? MakingChargesPerGram { get; set; }
        public decimal? TotalMakingCharges { get; set; }

        // Pricing
        public decimal ItemSubtotal { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal GSTPercentage { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal TotalAmount { get; set; }

        // Hallmark Info
        public bool IsHallmarked { get; set; }
        public string? HallmarkDetails { get; set; }
    }

    /// <summary>
    /// Payment details for the invoice
    /// </summary>
    public class InvoicePaymentDto
    {
        public long PaymentId { get; set; }
        public DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; } = string.Empty;
        public string? ReferenceNumber { get; set; }
        public decimal Amount { get; set; }
    }

    /// <summary>
    /// DTO for bulk invoice generation (multiple orders)
    /// </summary>
    public class BulkInvoiceRequestDto
    {
        public List<long> SaleOrderIds { get; set; } = new();
        public bool IncludePaymentDetails { get; set; } = true;
        public bool IncludeTermsAndConditions { get; set; } = true;
    }

    /// <summary>
    /// Response for bulk invoice generation
    /// </summary>
    public class BulkInvoiceResponseDto
    {
        public List<InvoiceResponseDto> Invoices { get; set; } = new();
        public int TotalGenerated { get; set; }
        public int TotalFailed { get; set; }
        public List<string> Errors { get; set; } = new();
    }
}
